databases:
  - name: exotic
    databaseName: exotic
    user: exotic_user

services:
  - type: web
    name: lazycars
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: exotic
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
